### ISSUE TITLE
מדוע בקריאת query לא מתקבל מספר התוצאות הקיימות?

### ISSUE THREAD

**Issue by gasner** [powerlink/Rest-API#1]
מדוע בקריאת query לא מתקבל מספר התוצאות הקיימות? "Total_Records"

**Comment by powerlink** [comment]
מספר התוצאות אינו מתקבל, אך בשאילתה אתה יכול לשלוט בכמות התוצאות שיופיעו בכל דף 
"page_size": 1,
ואז לדלג בין דפים על ידי הרצת אותה שאילתה וקידום מספר הדף 
"page_number": 2,

בכל פעם יש לבצע בדיקה שקיבלת נתונים ב 
data
כל עוד יש נתונים להמשיך להתקדם לדף הבא
