### ISSUE TITLE
php example error

### ISSUE THREAD

**Issue by ChaudEf** [powerlink/Rest-API#3]
יש הרבה שגיאות בקוד PHP

להלן הקוד המתוקן
`<?php

$data = '{
       "accountname" : "משה",
      "telephone1" : "036339060",
      "idnumber" : "1234",
      "billingcity" : "תל אביב"
        }';
$url='https://api.powerlink.co.il/api/record/account';
$data_string = json_encode($data);  
$curl = curl_init();
curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($curl, CURLOPT_POSTFIELDS, $data_string);                                                                   
curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($curl, CURLOPT_HTTPHEADER, array(                                                                          
    'Content-Type: application/json',
    'tokenid: ##################',                                                                                
    'Content-Length: ' . strlen($data_string))                                                                       
); 
$result = curl_exec($curl);
curl_close($curl);

`

**Comment by powerlink** [comment]
תודה רבה , נעדכן בהתאם
